//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finalMVC.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Book
    {
        public int idBook { get; set; }
        [Required(ErrorMessage ="Required")]
        public string bookName { get; set; }
        [Required(ErrorMessage = "Required")]
        public string Author { get; set; }
        [Required(ErrorMessage = "Required")]
        public string Year { get; set; }
       
    }
}
